name: Build, Test, and Publish QPdfSharp Libraries

on:
  workflow_dispatch:

jobs:
    build-test-version:
      name: Build, Test, and Version QPdfSharp Libraries
      outputs:
        qpdfsharp_version: ${{ steps.version-qpdfsharp.outputs.version }}
        qpdfsharp_changed: ${{ steps.version-qpdfsharp.outputs.changed }}
        qpdfsharp_interop_version: ${{ steps.version-qpdfsharp-interop.outputs.version }}
        qpdfsharp_interop_changed: ${{ steps.version-qpdfsharp-interop.outputs.changed }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.x'

        - name: Build Solution
          run: dotnet build ${GITHUB_WORKSPACE}

        - name: Test Solution
          run: dotnet test ${GITHUB_WORKSPACE}

        - name: Version QPdfSharp Library
          id: version-qpdfsharp
          uses: paulhatch/semantic-version@v5.3.0
          with:
            change_path: "src/QPdfSharp"

        - name: Version QPdfSharp.Interop Library
          id: version-qpdfsharp-interop
          uses: paulhatch/semantic-version@v5.3.0
          with:
            change_path: "src/QPdfSharp.Interop"
            major_pattern: "(MAJOR-INTEROP)"
            minor_pattern: "(MINOR-INTEROP)"
            namespace: Interop

        - name: Build QPdfSharp Libraries
          env:
            QPDFSHARP_VERSION: ${{ steps.version-qpdfsharp.outputs.version }}
            QPDFSHARP_INTEROP_VERSION: ${{ steps.version-qpdfsharp-interop.outputs.version }}
          run: "${GITHUB_WORKSPACE}/scripts/build-qpdfsharp-libraries-nuget.sh -p:QPdfSharpVersion=${QPDFSHARP_VERSION} -p:QPdfSharpInteropVersion=${QPDFSHARP_INTEROP_VERSION}"

        - name: Upload QPdfSharp Nuggets
          uses: actions/upload-artifact@v4
          with:
            name: QPdfSharp
            path: ${{ github.workspace }}/artifacts/QPdfSharp.[0-9]*.nupkg

        - name: Upload QPdfSharp.Interop Nuggets
          uses: actions/upload-artifact@v4
          with:
            name: QPdfSharp.Interop
            path: ${{ github.workspace }}/artifacts/QPdfSharp.Interop*.nupkg

    publish-qpdfsharp:
      if: needs.build-test-version.outputs.qpdfsharp_changed
      name: Publish QPdfSharp
      needs: build-test-version
      runs-on: ubuntu-latest
      steps:
        - name: Download QPdfSharp Nuggets
          uses: actions/download-artifact@v4
          with:
            name: QPdfSharp

        - name: Publish NuGet Package
          run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json ${GITHUB_WORKSPACE}/QPdfSharp*.nupkg

    publish-qpdfsharp-interop:
      if: needs.build-test-version.outputs.qpdfsharp_interop_changed
      name: Publish QPdfSharp.Interop
      needs: build-test-version
      runs-on: ubuntu-latest
      steps:
        - name: Download QPdfSharp.Interop  Nuggets
          uses: actions/download-artifact@v4
          with:
            name: QPdfSharp.Interop

        - name: Publish NuGet Package
          run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json ${GITHUB_WORKSPACE}/QPdfSharp.Interop*.nupkg

    create-gh-release:
      if: ${{ !failure() && !cancelled() && success('publish-qpdfsharp')  }}
      permissions:
        contents: write
      name: Create GitHub Release
      needs: [publish-qpdfsharp, build-test-version]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Changelog
          uses: actions/checkout@v4
          with:
            sparse-checkout: |
              RELEASE_NOTES.md
              CHANGELOG.md
            sparse-checkout-cone-mode: false

        - name: Download Nuggets
          uses: actions/download-artifact@v4
          with:
            pattern: QPdfSharp*
            merge-multiple: true

        - name: Update Changelog with Release Notes
          run: cat RELEASE_NOTES.md CHANGELOG.md > temp && mv temp CHANGELOG.md

        - uses: ncipollo/release-action@v1
          with:
            artifacts: "QPdfSharp,QPdfSharp.Interop"
            bodyFile: "RELEASE_NOTES.md"
            commit: ${{ github.sha }}
            generateReleaseNotes: true
            tag: v${{ needs.build-test-version.outputs.qpdfsharp_version }}

        - name: Update Changelog with Release Notes
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Update CHANGELOG.md with Release Notes"
