name: Build and Test QPdf

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:

  build-and-test:
    # TODO: Running on Windows until the next version of QPdf.RuntimeLibraries is released. Please change back after v 11.6.5
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build Solution
        run: dotnet build ${GITHUB_WORKSPACE}

      - name: Test Solution
        run: dotnet test ${GITHUB_WORKSPACE}

